"""Make url uniq

Revision ID: 0de58d9dadbe
Revises: c5ec11719388
Create Date: 2022-02-04 11:32:51.178321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de58d9dadbe'
down_revision = 'c5ec11719388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'qr_codes', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr_codes', type_='unique')
    # ### end Alembic commands ###
