"""Adding a experation date

Revision ID: 1cf5d1c1cce8
Revises: 92eb565d3486
Create Date: 2022-02-09 12:59:06.176554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf5d1c1cce8'
down_revision = '92eb565d3486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('expiration', sa.Interval(), nullable=True))
    op.add_column('qr_codes', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_codes', 'expiration_date')
    op.drop_column('qr_codes', 'expiration')
    # ### end Alembic commands ###
