"""Added a auth

Revision ID: 2ca1e9adbdde
Revises: de50c7ffa463
Create Date: 2022-02-14 11:46:31.040534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca1e9adbdde'
down_revision = 'de50c7ffa463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
