"""Updated a expiration date

Revision ID: 33325c15a64e
Revises: 1cf5d1c1cce8
Create Date: 2022-02-09 13:07:40.114663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33325c15a64e'
down_revision = '1cf5d1c1cce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
