"""Updated url address length

Revision ID: 417d2c0a2ca1
Revises: c4ccbbb4e77c
Create Date: 2022-02-05 10:34:04.432160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417d2c0a2ca1'
down_revision = 'c4ccbbb4e77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
