"""Added a auth model

Revision ID: 914a9d36c16a
Revises: 2ca1e9adbdde
Create Date: 2022-02-14 11:49:25.319619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914a9d36c16a'
down_revision = '2ca1e9adbdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=40), nullable=False),
    sa.Column('app_secret', sa.String(length=128), nullable=False),
    sa.Column('date_of_add', sa.DateTime(), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
