"""Updated date time

Revision ID: 92eb565d3486
Revises: d7ae5720e0f5
Create Date: 2022-02-07 11:35:53.321191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92eb565d3486'
down_revision = 'd7ae5720e0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
