"""Updated a models

Revision ID: 93cb79b1d372
Revises: c56b700fcaf7
Create Date: 2022-02-04 09:37:34.080989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93cb79b1d372'
down_revision = 'c56b700fcaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('qr_codes', sa.Column('date_of_add', sa.DateTime(), nullable=False))
    op.add_column('qr_codes', sa.Column('date_of_update', sa.DateTime(), nullable=False))
    op.alter_column('qr_codes', 'url',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.create_unique_constraint(None, 'qr_codes', ['name'])
    op.drop_column('qr_codes', 'date')
    op.drop_column('qr_codes', 'qr_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('qr_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('qr_codes', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'qr_codes', type_='unique')
    op.alter_column('qr_codes', 'url',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_column('qr_codes', 'date_of_update')
    op.drop_column('qr_codes', 'date_of_add')
    op.drop_column('qr_codes', 'name')
    # ### end Alembic commands ###
