"""Updated url address length

Revision ID: c4ccbbb4e77c
Revises: f188c349381b
Create Date: 2022-02-05 10:31:27.534983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ccbbb4e77c'
down_revision = 'f188c349381b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
