"""Updated a model

Revision ID: c5ec11719388
Revises: b8a464d89d6c
Create Date: 2022-02-04 10:40:54.283092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ec11719388'
down_revision = 'b8a464d89d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
