"""Updating model

Revision ID: c7c214ecc199
Revises: 0b68e8ad575a
Create Date: 2022-02-09 15:11:22.457344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c214ecc199'
down_revision = '0b68e8ad575a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('file_name', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_codes', 'file_name')
    # ### end Alembic commands ###
