"""Added a auth model

Revision ID: de50c7ffa463
Revises: 0f854b9c04dd
Create Date: 2022-02-14 11:42:59.181760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de50c7ffa463'
down_revision = '0f854b9c04dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
