"""Make url uniq

Revision ID: f188c349381b
Revises: fefb9bf571f7
Create Date: 2022-02-04 14:33:37.764104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f188c349381b'
down_revision = 'fefb9bf571f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('source_ip', sa.String(length=16), nullable=True))
    op.drop_column('qr_codes', 'user_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('user_ip', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('qr_codes', 'source_ip')
    # ### end Alembic commands ###
