"""Make url uniq

Revision ID: fefb9bf571f7
Revises: 0de58d9dadbe
Create Date: 2022-02-04 14:31:53.328397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefb9bf571f7'
down_revision = '0de58d9dadbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('qr_codes_name_key', 'qr_codes', type_='unique')
    op.drop_column('qr_codes', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('qr_codes_name_key', 'qr_codes', ['name'])
    # ### end Alembic commands ###
